# Usa la imagen oficial de MySQL
FROM mysql:8.0

# Configura el entorno para el contenedor
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=starsbar
ENV MYSQL_USER=mariocc
ENV MYSQL_PASSWORD=mariocc

# Expon el puerto 3306 para acceder a MySQL
EXPOSE 3306

# Volumen para persistir los datos
VOLUME /var/lib/mysql

# Comando por defecto para iniciar el contenedor de MySQL
CMD ["mysqld"]
