services:
  - type: web
    name: mysql-service
    env: docker
    dockerfilePath: ./Dockerfile.mysql
    ports:
      - 3306
      - 8080
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_USER
        value: mariocc
      - key: MYSQL_PASSWORD
        value: mariocc
      - key: MYSQL_DATABASE
        value: starsbar
