name: Build and Push Docker Images

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend image
      run: |
        docker build -t ghcr.io/martinezmario02/starsbar-backend:latest -f ./backend/Dockerfile.backend ./backend
        docker push ghcr.io/martinezmario02/starsbar-backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t ghcr.io/martinezmario02/starsbar-frontend:latest -f ./frontend/Dockerfile.frontend ./frontend
        docker push ghcr.io/martinezmario02/starsbar-frontend:latest
