name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Frontend Dockerfile Location
        run: |
          echo "Checking for dockerfile.frontend"
          ls -R

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image for Frontend
        run: docker build -f frontend/dockerfile.frontend -t ghcr.io/${{ github.actor }}/starsbar-frontend:latest .

      - name: Push Docker Image for Frontend
        run: docker push ghcr.io/${{ github.actor }}/starsbar-frontend:latest

  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Backend Dockerfile Location
        run: |
          echo "Checking for dockerfile.backend"
          ls -R

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image for Backend
        run: docker build -f backend/dockerfile.backend -t ghcr.io/${{ github.actor }}/starsbar-backend:latest .

      - name: Push Docker Image for Backend
        run: docker push ghcr.io/${{ github.actor }}/starsbar-backend:latest
